# Update interval in ticks (20 ticks = 1 second)
update-interval: 20

# TABLIST SETTINGS
# Supports: &a, &#FF0000, and <gradient>
header:
  - "<gradient:#ff0088:#aa00ff><bold> JustTAB Network </bold></gradient>"
  - "&7Welcome, &f<player>"

footer:
  - "&7Online: &f<online>"
  - "<rainbow>www.myserver.net</rainbow>"

# Tablist Name Format
# This supports LuckPerms prefixes/suffixes automatically
player-format: "<prefix><white><player><suffix>"

# SCOREBOARD SETTINGS
scoreboard:
  enabled: true
  title: "&b&lMY SERVER"
  lines:
    - "&7<date>"
    - ""
    - "&fName: &a<player>"
    - "&fRank: <prefix>"
    - ""
    - "&fPing: &e<ping>ms"
    - "&fTPS: &e<tps>"
    - ""
    - "<gradient:blue:aqua>play.server.net</gradient>"

messages:
  reload: "&aJustTAB configuration reloaded."
